### ISSUE TITLE
Passing any comparable function to `Heap.new(direction)`

### ISSUE THREAD

**Issue by rdrey** [jimsynz/heap#1]
Hey there

I would like to compare `DateTime`s as the keys in my Heap / Priority Queue. 

From the stacktrace it looks like I need to add a clause to `Heap.meld` that accepts something other than `:<` and `:>`. (I was passing `&Timex.before?/2`.)

Just checking if this project is still active and you'd like the contribution. All the other queues are too complicated for my liking (Processes / GenServers, etc.)

Thanks!
Rainer

**Comment by jimsynz** [comment]
Hi Rainer.

When I write this project I didn't really know much about Elixir, so I made it as simple as possible.  Your assumption is correct. It seems like it wouldn't be hard to make it so that you can pass a function as your comparator and use it in `Heap.meld`.  I've been meaning to go back and rip out espec as well, so maybe I should think about a new release.

**Comment by jimsynz** [comment]
Short answer - please feel free to send a PR :)

**Comment by jimsynz** [comment]
I've done some work in #2 to make things easier for you.

**Comment by rdrey** [comment]
Thanks a lot! I'm only using Elixir for fun in my evenings (and have plans tonight), but will work on this very soon. :)

**Comment by rdrey** [comment]
Fixed in #3 🎉

**Comment by rdrey** [comment]
Oh, one other thing that had me quite confused is the use of `:>` for `min()`: https://github.com/jamesotron/heap/blob/70f02120a4d91946db5755783765f56068b283f2/lib/heap.ex#L25 

I feel like a min heap is better represented by the smaller than sign (<). (And that's also how the new comparator works: `Heap.min() == Heap.new(&(&1 < &2))`) I left the code as is, though.

We probably can't change that without a major version bump, though.

**Comment by jimsynz** [comment]
Yeah. That was probably just a brain fart on my part :)

**Comment by jimsynz** [comment]
Which is to say I'm happy to fix it and bump the version :)

**Comment by jimsynz** [comment]
Closed by #3
